### ISSUE TITLE
[Tiled] Transparency does not work

### ISSUE THREAD

**Issue by alexeygritsenko** [craftworkgames/MonoGame.Extended#144]
Please Fix the opacity property
![opacity](https://cloud.githubusercontent.com/assets/10233486/13871788/2be977e4-ecf6-11e5-87af-0c494bbd0209.png)

**Comment by craftworkgames** [comment]
What version are you using?  I could be wrong but I have a feeling this is already fixed in the `develop` branch.

**Comment by alexeygritsenko** [comment]
lastet 0.4.64

**Comment by craftworkgames** [comment]
@alexeygritsenko Did you test the code in `develop`? If you don't want to download and build the code yourself you can always use the NuGet package from our build server.

    http://build.craftworkgames.com/guestAuth/app/nuget/v1/FeedService.svc/

**Comment by alexeygritsenko** [comment]
Yes thank you. I just wanted to ask where I can download the latest beta release.
However, your server address does not work. Why is there an older version of the exact same
![betaold](https://cloud.githubusercontent.com/assets/10233486/14010176/df97e990-f1a3-11e5-990e-31eb9f4cfb33.PNG)

**Comment by craftworkgames** [comment]
You're almost there. You just need to include pre-release packages.

![image](https://cloud.githubusercontent.com/assets/3201643/14010263/548d2aae-f1df-11e5-91bd-bd11b7477044.png)

**Comment by alexeygritsenko** [comment]
ok thanks, now I installed the latest beta of the example.
but a new problem now Tiled Maps
![betaerr](https://cloud.githubusercontent.com/assets/10233486/14010591/9f450900-f1a7-11e5-9b02-37b45986aa90.PNG)
 example does not start
Reading after the end of the stream is not possible.

**Comment by craftworkgames** [comment]
We've upgraded to use MonoGame 3.5.

**Comment by alexeygritsenko** [comment]
da ya tozhe
Yes, I, too,

**Comment by alexeygritsenko** [comment]
![vers](https://cloud.githubusercontent.com/assets/10233486/14010683/845e7bb6-f1a8-11e5-99b7-31e974f3f5ab.PNG)

**Comment by craftworkgames** [comment]
Ah well in that case I'm not sure. Try cleaning and rebuilding your content. Make sure it's the 3.5 version of the Pipeline tool.

**Comment by alexeygritsenko** [comment]
i update pipeline, but new error
![draw](https://cloud.githubusercontent.com/assets/10233486/14011188/95107e64-f1ad-11e5-9d80-1f0696e1edca.PNG)
Method not found Draw()

**Comment by craftworkgames** [comment]
@alexeygritsenko Sorry I didn't get back to you until now. I've had a really busy weekend so far.

The error still looks like an issue with referencing the wrong version of a DLL. Although, I can't really tell from the message what DLL it's referring too. My best guess is that it can't find a required method in the MonoGame DLL but I'm not sure.

It looks like you're trying to build the samples out of the Samples.Extended repository. I haven't updated those to MonoGame 3.5 yet so I'm not surprised it's a bit complicated. Rather than doing that I suggest you start with either the demos in the `develop` branch or create a brand new MonoGame 3.5 project from scratch.

Sorry this has been such a hassle for you. These issues should go away once we officially release the next version of MonoGame.Extended. Building it yourself without understanding how all the bits work can be a bit complicated.

**Comment by craftworkgames** [comment]
Fixed in #292

**Comment by johmarjac** [comment]
Hi, I referenced Extended and Pipeline v1.0.617 using NuGet Package Manager.
I got still the same issue, my tiles being drawn with a black background instead of transparency.
![grass](https://user-images.githubusercontent.com/30114127/34721100-b17e7a30-f541-11e7-94fe-b26e19e7d1e7.png)

**Comment by craftworkgames** [comment]
Maybe you haven't configured the `GraphicsDevice` correctly?

Take a look [at the demo](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/Demos/Demo.Features/Demos/TiledMapsDemo.cs#L166)

**Comment by Yothri** [comment]
I didnt set AlphaBlending, thanks for the hint! :)
